# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SATDBailiff CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test SATDBailiff Runs
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: satd
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Verify MySQL Database is set correctly
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --user=user --database=satd --port 3306 --password=root < sql/satd.sql
    - name: Acquiring Satd Detector
      run: |
        sudo mkdir lib
        sudo chmod +x ./lib
        sudo wget -N https://github.com/Tbabm/SATDDetector-Core/releases/download/v0.1/satd_detector.jar 
        sudo mv satd_detector.jar /home/runner/work/SATDBailiff/SATDBailiff/lib
    - name: Build tool
      run: mvn -B package --file pom.xml
